In [ ]:

# 11th December 2023
# CSC461 – Assignment4 – NLP
# Muhammad Anas
# Fa21-Bse-126


# import warnings to "ignore" warning messages

import warnings
warnings.filterwarnings("ignore")

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import pandas as pd
import numpy as np


In [ ]:
#generate three simple texts as reference

text_1 = "data science is one of the most important courses in computer science"
text_2 = "this is one of the best data science courses"
text_3 = "the data scientists perform data analysis"

In [ ]:
#combine both texts to make a corpus

data_exp1 = [text_1, text_2 , text_3]
data_exp1

['data science is one of the most important courses in computer science',
 'this is one of the best data science courses',
 'the data scientists perform data analysis']

In [ ]:
#create a reference object to the CountVectorizer constructor
#use the reference object to generate BoW matrix using the fit_transform() function

count_vectorizer = CountVectorizer()
c_vector_matrix_exp1 = count_vectorizer.fit_transform(data_exp1)
c_vector_matrix_exp1

<3x16 sparse matrix of type '<class 'numpy.int64'>'
	with 25 stored elements in Compressed Sparse Row format>

In [ ]:
#use get_feature_names_out() to extract vocabulary

c_tokens_exp1 = count_vectorizer.get_feature_names_out()
c_tokens_exp1

array(['analysis', 'best', 'computer', 'courses', 'data', 'important',
       'in', 'is', 'most', 'of', 'one', 'perform', 'science',
       'scientists', 'the', 'this'], dtype=object)

In [ ]:
#convert BoW matrix to an array format

c_vector_matrix_exp1.toarray()

array([[0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 0, 1, 0],
       [0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1],
       [1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0]])

In [ ]:
# @title Default title text
#convert BoW matrix to a Pandas dataframe

df_c_exp1 = pd.DataFrame(data = c_vector_matrix_exp1.toarray(), columns = c_tokens_exp1)
df_c_exp1

analysis  best  computer  courses  data  important  in  is  most  of  one  \
0         0     0         1        1     1          1   1   1     1   1    1   
1         0     1         0        1     1          0   0   1     0   1    1   
2         1     0         0        0     2          0   0   0     0   0    0   

   perform  science  scientists  the  this  
0        0        2           0    1     0  
1        0        1           0    1     1  
2        1        0           1    1     0

In [ ]:
tf = df_c_exp1.div(df_c_exp1.sum(axis=1), axis=0)

# Display the DataFrame in the same tabular format
print(tf)

   analysis      best  computer   courses      data  important        in  \
0  0.000000  0.000000  0.083333  0.083333  0.083333   0.083333  0.083333   
1  0.000000  0.111111  0.000000  0.111111  0.111111   0.000000  0.000000   
2  0.166667  0.000000  0.000000  0.000000  0.333333   0.000000  0.000000   

         is      most        of       one   perform   science  scientists  \
0  0.083333  0.083333  0.083333  0.083333  0.000000  0.166667    0.000000   
1  0.111111  0.000000  0.111111  0.111111  0.000000  0.111111    0.000000   
2  0.000000  0.000000  0.000000  0.000000  0.166667  0.000000    0.166667   

        the      this  
0  0.083333  0.000000  
1  0.111111  0.111111  
2  0.166667  0.000000  


In [ ]:
# Calculate IDF
# The number of documents
N = df_c_exp1.shape[0]

# Number of documents where the term appears
df = (df_c_exp1 > 0).sum(axis=0)

# Using log base 10
idf = np.log10(N / df) + 1

# Display the DataFrame in the same tabular format
print(idf)

analysis      1.477121
best          1.477121
computer      1.477121
courses       1.176091
data          1.000000
important     1.477121
in            1.477121
is            1.176091
most          1.477121
of            1.176091
one           1.176091
perform       1.477121
science       1.176091
scientists    1.477121
the           1.000000
this          1.477121
dtype: float64


In [ ]:
#generate cosine similarity matrix

c_cosine_similarity_matrix_exp1 = cosine_similarity(c_vector_matrix_exp1)
c_cosine_similarity_matrix_exp1

array([[1.        , 0.71269665, 0.28347335],
       [0.71269665, 1.        , 0.35355339],
       [0.28347335, 0.35355339, 1.        ]])

In [ ]:
#convert cosine similarity matrix to Pandas dataframe

df_c_similarity_exp1 = pd.DataFrame(data = c_cosine_similarity_matrix_exp1)
df_c_similarity_exp1

0         1         2
0  1.000000  0.712697  0.283473
1  0.712697  1.000000  0.353553
2  0.283473  0.353553  1.000000

In [ ]:
#create a reference object to the TfidfVectorizer constructor
#use the reference object to generate tf.idf matrix using the fit_transform() function

tfidf_vect_exp1 = TfidfVectorizer()
t_tfidf_matrix_exp1 = tfidf_vect_exp1.fit_transform(data_exp1)
t_tfidf_matrix_exp1

<3x16 sparse matrix of type '<class 'numpy.float64'>'
	with 25 stored elements in Compressed Sparse Row format>

In [ ]:
#use get_feature_names_out() to extract vocabulary

t_tokens_exp1 = tfidf_vect_exp1.get_feature_names_out()
t_tokens_exp1

array(['analysis', 'best', 'computer', 'courses', 'data', 'important',
       'in', 'is', 'most', 'of', 'one', 'perform', 'science',
       'scientists', 'the', 'this'], dtype=object)

In [ ]:
#convert tf.idf matrix to a Pandas dataframe

df_t_exp1 = pd.DataFrame(data = t_tfidf_matrix_exp1.toarray(), columns = t_tokens_exp1)
df_t_exp1

analysis      best  computer   courses      data  important        in  \
0  0.000000  0.000000  0.327476  0.249054  0.193412   0.327476  0.327476   
1  0.000000  0.422968  0.000000  0.321678  0.249812   0.000000  0.000000   
2  0.459115  0.000000  0.000000  0.000000  0.542321   0.000000  0.000000   

         is      most        of       one   perform   science  scientists  \
0  0.249054  0.327476  0.249054  0.249054  0.000000  0.498107    0.000000   
1  0.321678  0.000000  0.321678  0.321678  0.000000  0.321678    0.000000   
2  0.000000  0.000000  0.000000  0.000000  0.459115  0.000000    0.459115   

        the      this  
0  0.193412  0.000000  
1  0.249812  0.422968  
2  0.271161  0.000000

In [ ]:
#generate cosine similarity matrix

t_cosine_similarity_matrix_exp1 = cosine_similarity(t_tfidf_matrix_exp1)
t_cosine_similarity_matrix_exp1

array([[1.        , 0.57732419, 0.15733751],
       [0.57732419, 1.        , 0.20321737],
       [0.15733751, 0.20321737, 1.        ]])

In [ ]:
#convert cosine similarity matrix to Pandas dataframe

df_t_similarity_exp1 = pd.DataFrame(data = t_cosine_similarity_matrix_exp1)
df_t_similarity_exp1

0         1         2
0  1.000000  0.577324  0.157338
1  0.577324  1.000000  0.203217
2  0.157338  0.203217  1.000000

In [1]:
#import scityblock (manhattan distance) from scipy

from scipy.spatial.distance import cityblock

In [ ]:
#calculate scityblock (manhattan distance) between two document vectors (text1, text3)

cityblock(df_t_exp1.iloc[0], df_t_exp1.iloc[2],df_t_exp1.iloc[1])

0.5872747671823697

In [ ]:
#calculate percentage scityblock (manhattan distance)

1/(cityblock(df_t_exp1.iloc[1], df_t_exp1.iloc[2]))

0.24122367683062765

In [ ]:
#import math library to use euclidean distance

import math

In [ ]:
#calculate euclidean distance between two document vectors (text2, text3)

math.dist(df_t_exp1.iloc[1], df_t_exp1.iloc[2])

1.2623649438617415